// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"three","status":true,"description":"","parameters":{}},
{"name":"DotMoveSystem","status":true,"description":"ドット移動システム v1.9.6","parameters":{}},
{"name":"SuperMode7","status":true,"description":"SuperMode7 v0.1.0","parameters":{"DefaultParameter":"","OnBoatExecScript":"","OnShipExecScript":"","OnAirshipExecScript":"SMode7_ChangeCameraHeight(48 * 10, 60);\nSMode7_ChangeFarFromCenter(18, 60);\nSMode7_ChangeFadeEffect(1, 60);"}},
{"name":"SmoothCamera","status":true,"description":"なめらかカメラ v1.0.2","parameters":{"EnableSmoothCameraSwitchId":"0","MaxScrollFar":"8","MinScrollFar":"2","BaseScrollDiv":"32"}},
{"name":"TitleSkip","status":true,"description":"","parameters":{}}
];
